-- Database generated with pgModeler (PostgreSQL Database Modeler).
-- pgModeler  version: 0.8.1
-- PostgreSQL version: 9.4
-- Project Site: pgmodeler.com.br
-- Model Author: ---


-- Database creation must be done outside an multicommand file.
-- These commands were put in this file only for convenience.
-- -- object: novo_banco_de_dados | type: DATABASE --
-- -- DROP DATABASE IF EXISTS novo_banco_de_dados;
-- CREATE DATABASE novo_banco_de_dados
-- ;
-- -- ddl-end --
-- 

-- object: PERFIL | type: TABLE --
-- DROP TABLE IF EXISTS PERFIL CASCADE;
CREATE TABLE PERFIL(
	NOME varchar(100) PRIMARY KEY NOT NULL,
	DESCRICAO text NOT NULL
);

-- object: USUARIO | type: TABLE --
-- DROP TABLE IF EXISTS USUARIO CASCADE;
CREATE TABLE USUARIO(
	ID serial PRIMARY KEY NOT NULL,
	NOME varchar(100),
	EMAIL text NOT NULL,
	SENHA text NOT NULL,	
	PERFIL varchar(100) NOT NULL
);

-- object: BASE_TEXTO | type: TABLE --
-- DROP TABLE IF EXISTS BASE_TEXTO CASCADE;
CREATE TABLE BASE_TEXTO(
	ID serial PRIMARY KEY NOT NULL,
	TITULO text NOT NULL,
	DESCRICAO text NOT NULL,
	SUPERVISOR integer NOT NULL
);

-- object: ALOCACAO_TEXTO | type: TABLE --
-- DROP TABLE IF EXISTS ALOCACAO_TEXTO CASCADE;
CREATE TABLE ALOCACAO_TEXTO(
	ID serial PRIMARY KEY NOT NULL,
	BASE_TEXTO integer,
	TEXTO text,
	SUPERVISOR integer	
);

-- object: ESCOLHA_CLASSE_TEXTO | type: TABLE --
-- DROP TABLE IF EXISTS ESCOLHA_CLASSE_TEXTO CASCADE;
CREATE TABLE ESCOLHA_CLASSE_TEXTO(
	ID serial PRIMARY KEY NOT NULL,
	DESCRICAO varchar(200) NOT NULL,
	ALOCACAO_TEXTO integer NOT NULL
);

-- object: CLASSIFICACAO_TEXTO | type: TABLE --
-- DROP TABLE IF EXISTS CLASSIFICACAO_TEXTO CASCADE;
CREATE TABLE CLASSIFICACAO_TEXTO(
	ESCRAVO integer NOT NULL,
	ALOCACAO_TEXTO integer NOT NULL,
	ESCOLHA_TEXTO integer NOT NULL,
	CONSTRAINT CLASSIFICACAO_TEXTO_PK PRIMARY KEY (ESCRAVO,ALOCACAO_TEXTO,ESCOLHA_TEXTO)

);

-- object: LIBERACAO_BASE_TEXTO | type: TABLE --
-- DROP TABLE IF EXISTS LIBERACAO_BASE_TEXTO CASCADE;
CREATE TABLE LIBERACAO_BASE_TEXTO(
	BASE_TEXTO integer NOT NULL,
	SUPERVISOR integer NOT NULL,
	ESCRAVO integer NOT NULL,
	STATUS char NOT NULL,
	CONSTRAINT LIBERACAO_BASE_TEXTO_PK PRIMARY KEY (BASE_TEXTO,SUPERVISOR,ESCRAVO)

);

-- object: USUARIO_PERFIL_FK | type: CONSTRAINT --
-- ALTER TABLE USUARIO DROP CONSTRAINT IF EXISTS USUARIO_PERFIL_FK CASCADE;
ALTER TABLE USUARIO ADD CONSTRAINT USUARIO_PERFIL_FK FOREIGN KEY (PERFIL)
REFERENCES PERFIL (NOME) ON DELETE RESTRICT;
-- ddl-end --

-- object: BASE_TEXTO_SUPERVISOR_FK | type: CONSTRAINT --
-- ALTER TABLE BASE_TEXTO DROP CONSTRAINT IF EXISTS BASE_TEXTO_SUPERVISOR_FK CASCADE;
ALTER TABLE BASE_TEXTO ADD CONSTRAINT BASE_TEXTO_SUPERVISOR_FK FOREIGN KEY (SUPERVISOR)
REFERENCES USUARIO (ID)
ON DELETE RESTRICT;
-- ddl-end --

-- object: ALOCACAO_TEXTO_SUPERVISOR_FK | type: CONSTRAINT --
-- ALTER TABLE ALOCACAO_TEXTO DROP CONSTRAINT IF EXISTS ALOCACAO_TEXTO_SUPERVISOR_FK CASCADE;
ALTER TABLE ALOCACAO_TEXTO ADD CONSTRAINT ALOCACAO_TEXTO_SUPERVISOR_FK FOREIGN KEY (SUPERVISOR)
REFERENCES USUARIO (ID)
ON DELETE RESTRICT;
-- ddl-end --

-- object: ALOCACAO_TEXTO_BASE_TEXTO_FK | type: CONSTRAINT --
-- ALTER TABLE ALOCACAO_TEXTO DROP CONSTRAINT IF EXISTS ALOCACAO_TEXTO_BASE_TEXTO_FK CASCADE;
ALTER TABLE ALOCACAO_TEXTO ADD CONSTRAINT ALOCACAO_TEXTO_BASE_TEXTO_FK FOREIGN KEY (BASE_TEXTO)
REFERENCES BASE_TEXTO (ID)
ON DELETE RESTRICT;
-- ddl-end --

-- object: ESCOLHA_TEXTO_ALOCACAO_TEXTO_FK | type: CONSTRAINT --
-- ALTER TABLE ESCOLHA_CLASSE_TEXTO DROP CONSTRAINT IF EXISTS ESCOLHA_TEXTO_ALOCACAO_TEXTO_FK CASCADE;
ALTER TABLE ESCOLHA_CLASSE_TEXTO ADD CONSTRAINT ESCOLHA_TEXTO_ALOCACAO_TEXTO_FK FOREIGN KEY (ALOCACAO_TEXTO)
REFERENCES ALOCACAO_TEXTO (ID)
ON DELETE RESTRICT;
-- ddl-end --

-- object: CLASSIFICACAO_TEXTO_ESCRAVO_FK | type: CONSTRAINT --
-- ALTER TABLE CLASSIFICACAO_TEXTO DROP CONSTRAINT IF EXISTS CLASSIFICACAO_TEXTO_ESCRAVO_FK CASCADE;
ALTER TABLE CLASSIFICACAO_TEXTO ADD CONSTRAINT CLASSIFICACAO_TEXTO_ESCRAVO_FK FOREIGN KEY (ESCRAVO)
REFERENCES USUARIO (ID)
ON DELETE RESTRICT;
-- ddl-end --

-- object: CLASSIFICACAO_TEXTO_ALOCACAO_TEXTO_FK | type: CONSTRAINT --
-- ALTER TABLE CLASSIFICACAO_TEXTO DROP CONSTRAINT IF EXISTS CLASSIFICACAO_TEXTO_ALOCACAO_TEXTO_FK CASCADE;
ALTER TABLE CLASSIFICACAO_TEXTO ADD CONSTRAINT CLASSIFICACAO_TEXTO_ALOCACAO_TEXTO_FK FOREIGN KEY (ALOCACAO_TEXTO)
REFERENCES ALOCACAO_TEXTO (ID)
ON DELETE RESTRICT;
-- ddl-end --

-- object: CLASSIFICACAO_TEXTO_ESCOLHA_TEXTO_FK | type: CONSTRAINT --
-- ALTER TABLE CLASSIFICACAO_TEXTO DROP CONSTRAINT IF EXISTS CLASSIFICACAO_TEXTO_ESCOLHA_TEXTO_FK CASCADE;
ALTER TABLE CLASSIFICACAO_TEXTO ADD CONSTRAINT CLASSIFICACAO_TEXTO_ESCOLHA_TEXTO_FK FOREIGN KEY (ESCOLHA_TEXTO)
REFERENCES ESCOLHA_CLASSE_TEXTO (ID)
ON DELETE RESTRICT;
-- ddl-end --

-- object: LIBERACAO_BASE_TEXTO_SUPERVISOR_FK | type: CONSTRAINT --
-- ALTER TABLE LIBERACAO_BASE_TEXTO DROP CONSTRAINT IF EXISTS LIBERACAO_BASE_TEXTO_SUPERVISOR_FK CASCADE;
ALTER TABLE LIBERACAO_BASE_TEXTO ADD CONSTRAINT LIBERACAO_BASE_TEXTO_SUPERVISOR_FK FOREIGN KEY (SUPERVISOR)
REFERENCES USUARIO (ID)
ON DELETE RESTRICT;
-- ddl-end --

-- object: LIBERACAO_BASE_TEXTO_ESCRAVO_FK | type: CONSTRAINT --
-- ALTER TABLE LIBERACAO_BASE_TEXTO DROP CONSTRAINT IF EXISTS LIBERACAO_BASE_TEXTO_ESCRAVO_FK CASCADE;
ALTER TABLE LIBERACAO_BASE_TEXTO ADD CONSTRAINT LIBERACAO_BASE_TEXTO_ESCRAVO_FK FOREIGN KEY (ESCRAVO)
REFERENCES USUARIO (ID)
ON DELETE RESTRICT;
-- ddl-end --

-- object: LIBERACAO_BASE_TEXTO_BASE_TEXTO_FK | type: CONSTRAINT --
-- ALTER TABLE LIBERACAO_BASE_TEXTO DROP CONSTRAINT IF EXISTS LIBERACAO_BASE_TEXTO_BASE_TEXTO_FK CASCADE;
ALTER TABLE LIBERACAO_BASE_TEXTO ADD CONSTRAINT LIBERACAO_BASE_TEXTO_BASE_TEXTO_FK FOREIGN KEY (BASE_TEXTO)
REFERENCES BASE_TEXTO (ID)
ON DELETE RESTRICT;
-- ddl-end --


