package br.edu.ufrpe.uag.projetao.model;
// Generated 26/04/2016 23:17:23 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import br.edu.ufrpe.uag.projetao.annotations.Coluna;
import br.edu.ufrpe.uag.projetao.annotations.Tabela;
import br.edu.ufrpe.uag.projetao.interfaces.InterfaceBase;
import br.edu.ufrpe.uag.projetao.interfaces.InterfaceEntity;

/**
 * BaseTexto generated by hbm2java
 */
@Tabela
@Entity
@Table(name = "base_texto", schema = "public")
public class BaseTexto implements InterfaceEntity ,InterfaceBase{

    @Coluna(colunaPosicao = 0, colunaNome = "ID")
    private int id;
    @Coluna(colunaPosicao = 1, colunaNome = "Título")
    private String titulo;
    private String descricao;
    private Usuario usuario;
    private Set<AlocacaoTexto> alocacaoTextos = new HashSet<>(0);
    private Set<LiberacaoBaseTexto> liberacaoBaseTextos = new HashSet<>(0);

    public BaseTexto() {
    }

    public BaseTexto(int id, Usuario usuario, String titulo, String descricao) {
	this.id = id;
	this.usuario = usuario;
	this.titulo = titulo;
	this.descricao = descricao;
    }

    public BaseTexto(int id, Usuario usuario, String titulo, String descricao, Set<AlocacaoTexto> alocacaoTextos,
	    Set<LiberacaoBaseTexto> liberacaoBaseTextos) {
	this.id = id;
	this.usuario = usuario;
	this.titulo = titulo;
	this.descricao = descricao;
	this.alocacaoTextos = alocacaoTextos;
	this.liberacaoBaseTextos = liberacaoBaseTextos;
    }

    @Id

    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
	return this.id;
    }

    public void setId(int id) {
	this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "supervisor", nullable = false)
    public Usuario getUsuario() {
	return this.usuario;
    }

    public void setUsuario(Usuario usuario) {
	this.usuario = usuario;
    }

    @Column(name = "titulo", nullable = false)
    public String getTitulo() {
	return this.titulo;
    }

    public void setTitulo(String titulo) {
	this.titulo = titulo;
    }

    @Column(name = "descricao", nullable = false)
    public String getDescricao() {
	return this.descricao;
    }

    public void setDescricao(String descricao) {
	this.descricao = descricao;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "baseTexto", cascade = CascadeType.REMOVE)
    public Set<AlocacaoTexto> getAlocacaoTextos() {
	return this.alocacaoTextos;
    }

    public void setAlocacaoTextos(Set<AlocacaoTexto> alocacaoTextos) {
	this.alocacaoTextos = alocacaoTextos;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "baseTexto", cascade = CascadeType.REMOVE)
    public Set<LiberacaoBaseTexto> getLiberacaoBaseTextos() {
	return this.liberacaoBaseTextos;
    }

    public void setLiberacaoBaseTextos(Set<LiberacaoBaseTexto> liberacaoBaseTextos) {
	this.liberacaoBaseTextos = liberacaoBaseTextos;
    }

    @Override
    public int hashCode() {
	int hash = 3;
	hash = 53 * hash + Objects.hashCode(this.usuario);
	hash = 53 * hash + Objects.hashCode(this.titulo);
	hash = 53 * hash + Objects.hashCode(this.descricao);
	return hash;
    }

    @Override
    public boolean equals(Object obj) {
	if (this == obj) {
	    return true;
	}
	if (obj == null) {
	    return false;
	}
	if (getClass() != obj.getClass()) {
	    return false;
	}
	final BaseTexto other = (BaseTexto) obj;
	if (!Objects.equals(this.titulo, other.titulo)) {
	    return false;
	}
	if (!Objects.equals(this.descricao, other.descricao)) {
	    return false;
	}
	return Objects.equals(this.usuario, other.usuario);
    }

    @Override
    public String toString() {
	return "[" + id + "]" + titulo;
    }

}
