package br.edu.ufrpe.uag.projetao.model;
// Generated 15/06/2016 11:29:14 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import br.edu.ufrpe.uag.projetao.interfaces.InterfaceEntity;

/**
 * BaseVideoDeteccao generated by hbm2java
 */
@Entity
@Table(name = "base_video_deteccao", schema = "public")
public class BaseVideoDeteccao implements InterfaceEntity{

    private int id;
    private Usuario usuario;
    private String titulo;
    private String descricao;
    private Set<LiberacaoBaseVideoDeteccao> liberacaoBaseVideoDeteccaos = new HashSet<LiberacaoBaseVideoDeteccao>(0);
    private Set<AlocacaoVideoDeteccao> alocacaoVideoDeteccaos = new HashSet<AlocacaoVideoDeteccao>(0);

    public BaseVideoDeteccao() {
    }

    public BaseVideoDeteccao(int id, Usuario usuario, String titulo, String descricao) {
	this.id = id;
	this.usuario = usuario;
	this.titulo = titulo;
	this.descricao = descricao;
    }

    public BaseVideoDeteccao(int id, Usuario usuario, String titulo, String descricao,
	    Set<LiberacaoBaseVideoDeteccao> liberacaoBaseVideoDeteccaos,
	    Set<AlocacaoVideoDeteccao> alocacaoVideoDeteccaos) {
	this.id = id;
	this.usuario = usuario;
	this.titulo = titulo;
	this.descricao = descricao;
	this.liberacaoBaseVideoDeteccaos = liberacaoBaseVideoDeteccaos;
	this.alocacaoVideoDeteccaos = alocacaoVideoDeteccaos;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
	return this.id;
    }

    public void setId(int id) {
	this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "supervisor", nullable = false)
    public Usuario getUsuario() {
	return this.usuario;
    }

    public void setUsuario(Usuario usuario) {
	this.usuario = usuario;
    }

    @Column(name = "titulo", nullable = false)
    public String getTitulo() {
	return this.titulo;
    }

    public void setTitulo(String titulo) {
	this.titulo = titulo;
    }

    @Column(name = "descricao", nullable = false)
    public String getDescricao() {
	return this.descricao;
    }

    public void setDescricao(String descricao) {
	this.descricao = descricao;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "baseVideoDeteccao")
    public Set<LiberacaoBaseVideoDeteccao> getLiberacaoBaseVideoDeteccaos() {
	return this.liberacaoBaseVideoDeteccaos;
    }

    public void setLiberacaoBaseVideoDeteccaos(Set<LiberacaoBaseVideoDeteccao> liberacaoBaseVideoDeteccaos) {
	this.liberacaoBaseVideoDeteccaos = liberacaoBaseVideoDeteccaos;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "baseVideoDeteccao")
    public Set<AlocacaoVideoDeteccao> getAlocacaoVideoDeteccaos() {
	return this.alocacaoVideoDeteccaos;
    }

    public void setAlocacaoVideoDeteccaos(Set<AlocacaoVideoDeteccao> alocacaoVideoDeteccaos) {
	this.alocacaoVideoDeteccaos = alocacaoVideoDeteccaos;
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.lang.Object#hashCode()
     */
    @Override
    public int hashCode() {
	final int prime = 31;
	int result = 1;
	result = prime * result + ((descricao == null) ? 0 : descricao.hashCode());
	result = prime * result + id;
	result = prime * result + ((titulo == null) ? 0 : titulo.hashCode());
	result = prime * result + ((usuario == null) ? 0 : usuario.hashCode());
	return result;
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.lang.Object#equals(java.lang.Object)
     */
    @Override
    public boolean equals(Object obj) {
	if (this == obj) {
	    return true;
	}
	if (obj == null) {
	    return false;
	}
	if (!(obj instanceof BaseVideoDeteccao)) {
	    return false;
	}
	BaseVideoDeteccao other = (BaseVideoDeteccao) obj;
	if (descricao == null) {
	    if (other.descricao != null) {
		return false;
	    }
	} else if (!descricao.equals(other.descricao)) {
	    return false;
	}
	if (id != other.id) {
	    return false;
	}
	if (titulo == null) {
	    if (other.titulo != null) {
		return false;
	    }
	} else if (!titulo.equals(other.titulo)) {
	    return false;
	}
	if (usuario == null) {
	    if (other.usuario != null) {
		return false;
	    }
	} else if (!usuario.equals(other.usuario)) {
	    return false;
	}
	return true;
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
	return titulo;
    }

}
