package br.edu.ufrpe.uag.projetao.model;
// Generated 27/05/2016 19:57:54 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import br.edu.ufrpe.uag.projetao.interfaces.InterfaceBase;
import br.edu.ufrpe.uag.projetao.interfaces.InterfaceEntity;

/**
 * BaseImagemDeteccao generated by hbm2java
 */
@Entity
@Table(name = "base_imagem_deteccao", schema = "public")
public class BaseImagemDeteccao implements InterfaceEntity, InterfaceBase {

    private int id;
    private Usuario usuario;
    private String titulo;
    private String descricao;
    private Set<AlocacaoImagemDeteccao> alocacaoImagemDeteccaos = new HashSet<AlocacaoImagemDeteccao>(0);
    private Set<LiberacaoBaseImagemDeteccao> liberacaoBaseImagemDeteccaos = new HashSet<LiberacaoBaseImagemDeteccao>(0);

    public BaseImagemDeteccao() {
    }

    public BaseImagemDeteccao(int id, Usuario usuario, String titulo, String descricao) {
	this.id = id;
	this.usuario = usuario;
	this.titulo = titulo;
	this.descricao = descricao;
    }

    public BaseImagemDeteccao(int id, Usuario usuario, String titulo, String descricao,
	    Set<AlocacaoImagemDeteccao> alocacaoImagemDeteccaos,
	    Set<LiberacaoBaseImagemDeteccao> liberacaoBaseImagemDeteccaos) {
	this.id = id;
	this.usuario = usuario;
	this.titulo = titulo;
	this.descricao = descricao;
	this.alocacaoImagemDeteccaos = alocacaoImagemDeteccaos;
	this.liberacaoBaseImagemDeteccaos = liberacaoBaseImagemDeteccaos;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
	return this.id;
    }

    public void setId(int id) {
	this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "supervisor", nullable = false)
    public Usuario getUsuario() {
	return this.usuario;
    }

    public void setUsuario(Usuario usuario) {
	this.usuario = usuario;
    }

    @Column(name = "titulo", nullable = false)
    public String getTitulo() {
	return this.titulo;
    }

    public void setTitulo(String titulo) {
	this.titulo = titulo;
    }

    @Column(name = "descricao", nullable = false)
    public String getDescricao() {
	return this.descricao;
    }

    public void setDescricao(String descricao) {
	this.descricao = descricao;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "baseImagemDeteccao")
    public Set<AlocacaoImagemDeteccao> getAlocacaoImagemDeteccaos() {
	return this.alocacaoImagemDeteccaos;
    }

    public void setAlocacaoImagemDeteccaos(Set<AlocacaoImagemDeteccao> alocacaoImagemDeteccaos) {
	this.alocacaoImagemDeteccaos = alocacaoImagemDeteccaos;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "baseImagemDeteccao")
    public Set<LiberacaoBaseImagemDeteccao> getLiberacaoBaseImagemDeteccaos() {
	return this.liberacaoBaseImagemDeteccaos;
    }

    public void setLiberacaoBaseImagemDeteccaos(Set<LiberacaoBaseImagemDeteccao> liberacaoBaseImagemDeteccaos) {
	this.liberacaoBaseImagemDeteccaos = liberacaoBaseImagemDeteccaos;
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.lang.Object#hashCode()
     */
    @Override
    public int hashCode() {
	final int prime = 31;
	int result = 1;
	result = prime * result + ((descricao == null) ? 0 : descricao.hashCode());
	result = prime * result + id;
	result = prime * result + ((titulo == null) ? 0 : titulo.hashCode());
	result = prime * result + ((usuario == null) ? 0 : usuario.hashCode());
	return result;
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.lang.Object#equals(java.lang.Object)
     */
    @Override
    public boolean equals(Object obj) {
	if (this == obj) {
	    return true;
	}
	if (obj == null) {
	    return false;
	}
	if (!(obj instanceof BaseImagemDeteccao)) {
	    return false;
	}
	BaseImagemDeteccao other = (BaseImagemDeteccao) obj;
	if (descricao == null) {
	    if (other.descricao != null) {
		return false;
	    }
	} else if (!descricao.equals(other.descricao)) {
	    return false;
	}
	if (id != other.id) {
	    return false;
	}
	if (titulo == null) {
	    if (other.titulo != null) {
		return false;
	    }
	} else if (!titulo.equals(other.titulo)) {
	    return false;
	}
	if (usuario == null) {
	    if (other.usuario != null) {
		return false;
	    }
	} else if (!usuario.equals(other.usuario)) {
	    return false;
	}
	return true;
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
	return this.titulo;
    }

}
