package br.edu.ufrpe.uag.projetao.model;
// Generated 20/04/2016 11:43:59 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ClassificacaoTextoId generated by hbm2java
 */
@Embeddable
public class ClassificacaoTextoId implements java.io.Serializable {

    private int escravo;
    private int alocacaoTexto;
    private int escolhaTexto;

    public ClassificacaoTextoId() {
    }

    public ClassificacaoTextoId(int escravo, int alocacaoTexto, int escolhaTexto) {
        this.escravo = escravo;
        this.alocacaoTexto = alocacaoTexto;
        this.escolhaTexto = escolhaTexto;
    }

    @Column(name = "escravo", nullable = false)
    public int getEscravo() {
        return this.escravo;
    }

    public void setEscravo(int escravo) {
        this.escravo = escravo;
    }

    @Column(name = "alocacao_texto", nullable = false)
    public int getAlocacaoTexto() {
        return this.alocacaoTexto;
    }

    public void setAlocacaoTexto(int alocacaoTexto) {
        this.alocacaoTexto = alocacaoTexto;
    }

    @Column(name = "escolha_texto", nullable = false)
    public int getEscolhaTexto() {
        return this.escolhaTexto;
    }

    public void setEscolhaTexto(int escolhaTexto) {
        this.escolhaTexto = escolhaTexto;
    }

    @Override
    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof ClassificacaoTextoId)) {
            return false;
        }
        ClassificacaoTextoId castOther = (ClassificacaoTextoId) other;

        return (this.getEscravo() == castOther.getEscravo())
                && (this.getAlocacaoTexto() == castOther.getAlocacaoTexto())
                && (this.getEscolhaTexto() == castOther.getEscolhaTexto());
    }

    @Override
    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getEscravo();
        result = 37 * result + this.getAlocacaoTexto();
        result = 37 * result + this.getEscolhaTexto();
        return result;
    }

    @Override
    public String toString() {
        return "ClassificacaoTextoId{" + "escravo=" + escravo + ", alocacaoTexto=" + alocacaoTexto + ", escolhaTexto=" + escolhaTexto + '}';
    }

}
