package br.edu.ufrpe.uag.projetao.model;
// Generated 27/05/2016 19:57:54 by Hibernate Tools 4.3.1

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import br.edu.ufrpe.uag.projetao.interfaces.InterfaceEntity;

/**
 * DeteccaoImagem generated by hbm2java
 */
@Entity
@Table(name = "deteccao_imagem", schema = "public")
public class DeteccaoImagem implements InterfaceEntity{

    private double x1;
    private double y1;
    private double x2;
    private double y2;
    private AlocacaoImagemDeteccao alocacaoImagemDeteccao;
    private Usuario usuario;

    public DeteccaoImagem() {
    }

    @Id
    @Column(name = "x1", unique = true, nullable = false)
    public double getX1() {
	return x1;
    }

    /**
     * @param x1
     *            the x1 to set
     */
    public void setX1(double x1) {
	this.x1 = x1;
    }

    @Id
    @Column(name = "y1", unique = true, nullable = false)
    public double getY1() {
	return y1;
    }

    /**
     * @param y1
     *            the y1 to set
     */
    public void setY1(double y1) {
	this.y1 = y1;
    }

    @Id
    @Column(name = "x2", unique = true, nullable = false)
    public double getX2() {
	return x2;
    }

    /**
     * @param x2
     *            the x2 to set
     */
    public void setX2(double x2) {
	this.x2 = x2;
    }

    @Id
    @Column(name = "y2", unique = true, nullable = false)
    public double getY2() {
	return y2;
    }

    /**
     * @param y2
     *            the y2 to set
     */
    public void setY2(double y2) {
	this.y2 = y2;
    }

    @Id
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "alocacao_imagem_detecccao", nullable = false, insertable = false, updatable = false)
    public AlocacaoImagemDeteccao getAlocacaoImagemDeteccao() {
	return this.alocacaoImagemDeteccao;
    }

    public void setAlocacaoImagemDeteccao(AlocacaoImagemDeteccao alocacaoImagemDeteccao) {
	this.alocacaoImagemDeteccao = alocacaoImagemDeteccao;
    }

    @Id
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "escravo", nullable = false, insertable = false, updatable = false)
    public Usuario getUsuario() {
	return this.usuario;
    }

    public void setUsuario(Usuario usuario) {
	this.usuario = usuario;
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.lang.Object#hashCode()
     */
    @Override
    public int hashCode() {
	final int prime = 31;
	int result = 1;
	result = prime * result + ((alocacaoImagemDeteccao == null) ? 0 : alocacaoImagemDeteccao.hashCode());
	result = prime * result + ((usuario == null) ? 0 : usuario.hashCode());
	long temp;
	temp = Double.doubleToLongBits(x1);
	result = prime * result + (int) (temp ^ (temp >>> 32));
	temp = Double.doubleToLongBits(x2);
	result = prime * result + (int) (temp ^ (temp >>> 32));
	temp = Double.doubleToLongBits(y1);
	result = prime * result + (int) (temp ^ (temp >>> 32));
	temp = Double.doubleToLongBits(y2);
	result = prime * result + (int) (temp ^ (temp >>> 32));
	return result;
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.lang.Object#equals(java.lang.Object)
     */
    @Override
    public boolean equals(Object obj) {
	if (this == obj) {
	    return true;
	}
	if (obj == null) {
	    return false;
	}
	if (!(obj instanceof DeteccaoImagem)) {
	    return false;
	}
	DeteccaoImagem other = (DeteccaoImagem) obj;
	if (alocacaoImagemDeteccao == null) {
	    if (other.alocacaoImagemDeteccao != null) {
		return false;
	    }
	} else if (!alocacaoImagemDeteccao.equals(other.alocacaoImagemDeteccao)) {
	    return false;
	}
	if (usuario == null) {
	    if (other.usuario != null) {
		return false;
	    }
	} else if (!usuario.equals(other.usuario)) {
	    return false;
	}
	if (Double.doubleToLongBits(x1) != Double.doubleToLongBits(other.x1)) {
	    return false;
	}
	if (Double.doubleToLongBits(x2) != Double.doubleToLongBits(other.x2)) {
	    return false;
	}
	if (Double.doubleToLongBits(y1) != Double.doubleToLongBits(other.y1)) {
	    return false;
	}
	if (Double.doubleToLongBits(y2) != Double.doubleToLongBits(other.y2)) {
	    return false;
	}
	return true;
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
	return "[(" + x1 + "," + y1 + "),(" + x2 + "," + y2 + ")]";
    }

}
