package br.edu.ufrpe.uag.projetao.model;
// Generated 15/06/2016 11:29:14 by Hibernate Tools 4.3.1

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import br.edu.ufrpe.uag.projetao.interfaces.InterfaceEntity;

/**
 * DeteccaoVideo generated by hbm2java
 */
@Entity
@Table(name = "deteccao_video", schema = "public")
public class DeteccaoVideo implements InterfaceEntity {

    private AlocacaoVideoDeteccao alocacaoVideoDeteccao;
    private Usuario usuario;

    public DeteccaoVideo() {
    }

    @Id
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "alocacao_video_deteccao", nullable = false)
    public AlocacaoVideoDeteccao getAlocacaoVideoDeteccao() {
	return this.alocacaoVideoDeteccao;
    }

    public void setAlocacaoVideoDeteccao(AlocacaoVideoDeteccao alocacaoVideoDeteccao) {
	this.alocacaoVideoDeteccao = alocacaoVideoDeteccao;
    }

    @Id
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "escravo", nullable = false)
    public Usuario getUsuario() {
	return this.usuario;
    }

    public void setUsuario(Usuario usuario) {
	this.usuario = usuario;
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.lang.Object#hashCode()
     */
    @Override
    public int hashCode() {
	final int prime = 31;
	int result = 1;
	result = prime * result + ((alocacaoVideoDeteccao == null) ? 0 : alocacaoVideoDeteccao.hashCode());
	result = prime * result + ((usuario == null) ? 0 : usuario.hashCode());
	return result;
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.lang.Object#equals(java.lang.Object)
     */
    @Override
    public boolean equals(Object obj) {
	if (this == obj) {
	    return true;
	}
	if (obj == null) {
	    return false;
	}
	if (!(obj instanceof DeteccaoVideo)) {
	    return false;
	}
	DeteccaoVideo other = (DeteccaoVideo) obj;
	if (alocacaoVideoDeteccao == null) {
	    if (other.alocacaoVideoDeteccao != null) {
		return false;
	    }
	} else if (!alocacaoVideoDeteccao.equals(other.alocacaoVideoDeteccao)) {
	    return false;
	}
	if (usuario == null) {
	    if (other.usuario != null) {
		return false;
	    }
	} else if (!usuario.equals(other.usuario)) {
	    return false;
	}
	return true;
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
	return "DeteccaoVideo [alocacaoVideoDeteccao=" + alocacaoVideoDeteccao + ", usuario=" + usuario + "]";
    }

}
