package br.edu.ufrpe.uag.projetao.model;
// Generated 20/04/2016 11:43:59 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LiberacaoBaseTextoId generated by hbm2java
 */
@Embeddable
public class LiberacaoBaseTextoId implements java.io.Serializable {

    private int baseTexto;
    private int supervisor;
    private int escravo;

    public LiberacaoBaseTextoId() {
    }

    public LiberacaoBaseTextoId(int baseTexto, int supervisor, int escravo) {
        this.baseTexto = baseTexto;
        this.supervisor = supervisor;
        this.escravo = escravo;
    }

    @Column(name = "base_texto", nullable = false)
    public int getBaseTexto() {
        return this.baseTexto;
    }

    public void setBaseTexto(int baseTexto) {
        this.baseTexto = baseTexto;
    }

    @Column(name = "supervisor", nullable = false)
    public int getSupervisor() {
        return this.supervisor;
    }

    public void setSupervisor(int supervisor) {
        this.supervisor = supervisor;
    }

    @Column(name = "escravo", nullable = false)
    public int getEscravo() {
        return this.escravo;
    }

    public void setEscravo(int escravo) {
        this.escravo = escravo;
    }

    @Override
    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof LiberacaoBaseTextoId)) {
            return false;
        }
        LiberacaoBaseTextoId castOther = (LiberacaoBaseTextoId) other;

        return (this.getBaseTexto() == castOther.getBaseTexto())
                && (this.getSupervisor() == castOther.getSupervisor())
                && (this.getEscravo() == castOther.getEscravo());
    }

    @Override
    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getBaseTexto();
        result = 37 * result + this.getSupervisor();
        result = 37 * result + this.getEscravo();
        return result;
    }

    @Override
    public String toString() {
        return "LiberacaoBaseTextoId{" + "baseTexto=" + baseTexto + ", supervisor=" + supervisor + ", escravo=" + escravo + '}';
    }

}
