package br.edu.ufrpe.uag.projetao.model;
// Generated 26/04/2016 23:17:23 by Hibernate Tools 4.3.1

import br.edu.ufrpe.uag.projetao.interfaces.InterfaceEntity;
import java.util.Objects;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * LiberacaoBaseImagemClasse generated by hbm2java
 */
@Entity
@Table(name = "liberacao_base_imagem_classe", schema = "public"
)
public class LiberacaoBaseImagemClasse implements java.io.Serializable, InterfaceEntity {

    private LiberacaoBaseImagemClasseId id;
    private BaseImagemClasse baseImagemClasse;
    private Usuario usuarioByEscravo;
    private Usuario usuarioBySupervisor;
    private char status;

    public LiberacaoBaseImagemClasse() {
    }

    public LiberacaoBaseImagemClasse(LiberacaoBaseImagemClasseId id, BaseImagemClasse baseImagemClasse, Usuario usuarioByEscravo, Usuario usuarioBySupervisor, char status) {
        this.id = id;
        this.baseImagemClasse = baseImagemClasse;
        this.usuarioByEscravo = usuarioByEscravo;
        this.usuarioBySupervisor = usuarioBySupervisor;
        this.status = status;
    }

    @EmbeddedId

    @AttributeOverrides({
        @AttributeOverride(name = "baseImagem", column = @Column(name = "base_imagem", nullable = false)),
        @AttributeOverride(name = "supervisor", column = @Column(name = "supervisor", nullable = false)),
        @AttributeOverride(name = "escravo", column = @Column(name = "escravo", nullable = false))})
    public LiberacaoBaseImagemClasseId getId() {
        return this.id;
    }

    public void setId(LiberacaoBaseImagemClasseId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "base_imagem", nullable = false, insertable = false, updatable = false)
    public BaseImagemClasse getBaseImagemClasse() {
        return this.baseImagemClasse;
    }

    public void setBaseImagemClasse(BaseImagemClasse baseImagemClasse) {
        this.baseImagemClasse = baseImagemClasse;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "escravo", nullable = false, insertable = false, updatable = false)
    public Usuario getUsuarioByEscravo() {
        return this.usuarioByEscravo;
    }

    public void setUsuarioByEscravo(Usuario usuarioByEscravo) {
        this.usuarioByEscravo = usuarioByEscravo;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "supervisor", nullable = false, insertable = false, updatable = false)
    public Usuario getUsuarioBySupervisor() {
        return this.usuarioBySupervisor;
    }

    public void setUsuarioBySupervisor(Usuario usuarioBySupervisor) {
        this.usuarioBySupervisor = usuarioBySupervisor;
    }

    @Column(name = "status", nullable = false, length = 1)
    public char getStatus() {
        return this.status;
    }

    public void setStatus(char status) {
        this.status = status;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 79 * hash + Objects.hashCode(this.id);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final LiberacaoBaseImagemClasse other = (LiberacaoBaseImagemClasse) obj;
        return Objects.equals(this.id, other.id);
    }

    @Override
    public String toString() {
        return "LiberacaoBaseImagemClasse{" + "baseImagemClasse=" + baseImagemClasse + ", usuarioByEscravo=" + usuarioByEscravo + ", usuarioBySupervisor=" + usuarioBySupervisor + ", status=" + status + '}';
    }

}
