package br.edu.ufrpe.uag.projetao.model;
// Generated 26/04/2016 23:17:23 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LiberacaoBaseImagemClasseId generated by hbm2java
 */
@Embeddable
public class LiberacaoBaseImagemClasseId implements java.io.Serializable {

    private int baseImagem;
    private int supervisor;
    private int escravo;

    public LiberacaoBaseImagemClasseId() {
    }

    public LiberacaoBaseImagemClasseId(int baseImagem, int supervisor, int escravo) {
        this.baseImagem = baseImagem;
        this.supervisor = supervisor;
        this.escravo = escravo;
    }

    @Column(name = "base_imagem", nullable = false)
    public int getBaseImagem() {
        return this.baseImagem;
    }

    public void setBaseImagem(int baseImagem) {
        this.baseImagem = baseImagem;
    }

    @Column(name = "supervisor", nullable = false)
    public int getSupervisor() {
        return this.supervisor;
    }

    public void setSupervisor(int supervisor) {
        this.supervisor = supervisor;
    }

    @Column(name = "escravo", nullable = false)
    public int getEscravo() {
        return this.escravo;
    }

    public void setEscravo(int escravo) {
        this.escravo = escravo;
    }

    @Override
    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof LiberacaoBaseImagemClasseId)) {
            return false;
        }
        LiberacaoBaseImagemClasseId castOther = (LiberacaoBaseImagemClasseId) other;

        return (this.getBaseImagem() == castOther.getBaseImagem())
                && (this.getSupervisor() == castOther.getSupervisor())
                && (this.getEscravo() == castOther.getEscravo());
    }

    @Override
    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getBaseImagem();
        result = 37 * result + this.getSupervisor();
        result = 37 * result + this.getEscravo();
        return result;
    }

}
