package br.edu.ufrpe.uag.projetao.model;
// Generated 15/06/2016 11:29:14 by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import br.edu.ufrpe.uag.projetao.interfaces.InterfaceEntity;

/**
 * LiberacaoBaseVideoDeteccao generated by hbm2java
 */
@Entity
@Table(name = "liberacao_base_video_deteccao", schema = "public")
public class LiberacaoBaseVideoDeteccao implements InterfaceEntity {

    private BaseVideoDeteccao baseVideoDeteccao;
    private Usuario usuarioBySupervisor;
    private Usuario usuarioByEscravo;
    private char status;

    public LiberacaoBaseVideoDeteccao() {
    }

    @Id
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "base_video_deteccao", nullable = false)
    public BaseVideoDeteccao getBaseVideoDeteccao() {
	return this.baseVideoDeteccao;
    }

    public void setBaseVideoDeteccao(BaseVideoDeteccao baseVideoDeteccao) {
	this.baseVideoDeteccao = baseVideoDeteccao;
    }

    @Id
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "supervisor", nullable = false)
    public Usuario getUsuarioBySupervisor() {
	return this.usuarioBySupervisor;
    }

    public void setUsuarioBySupervisor(Usuario usuarioBySupervisor) {
	this.usuarioBySupervisor = usuarioBySupervisor;
    }

    @Id
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "escravo", nullable = false)
    public Usuario getUsuarioByEscravo() {
	return this.usuarioByEscravo;
    }

    public void setUsuarioByEscravo(Usuario usuarioByEscravo) {
	this.usuarioByEscravo = usuarioByEscravo;
    }

    @Column(name = "status", nullable = false, length = 1)
    public char getStatus() {
	return this.status;
    }

    public void setStatus(char status) {
	this.status = status;
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.lang.Object#hashCode()
     */
    @Override
    public int hashCode() {
	final int prime = 31;
	int result = 1;
	result = prime * result + ((baseVideoDeteccao == null) ? 0 : baseVideoDeteccao.hashCode());
	result = prime * result + status;
	result = prime * result + ((usuarioByEscravo == null) ? 0 : usuarioByEscravo.hashCode());
	result = prime * result + ((usuarioBySupervisor == null) ? 0 : usuarioBySupervisor.hashCode());
	return result;
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.lang.Object#equals(java.lang.Object)
     */
    @Override
    public boolean equals(Object obj) {
	if (this == obj) {
	    return true;
	}
	if (obj == null) {
	    return false;
	}
	if (!(obj instanceof LiberacaoBaseVideoDeteccao)) {
	    return false;
	}
	LiberacaoBaseVideoDeteccao other = (LiberacaoBaseVideoDeteccao) obj;
	if (baseVideoDeteccao == null) {
	    if (other.baseVideoDeteccao != null) {
		return false;
	    }
	} else if (!baseVideoDeteccao.equals(other.baseVideoDeteccao)) {
	    return false;
	}
	if (status != other.status) {
	    return false;
	}
	if (usuarioByEscravo == null) {
	    if (other.usuarioByEscravo != null) {
		return false;
	    }
	} else if (!usuarioByEscravo.equals(other.usuarioByEscravo)) {
	    return false;
	}
	if (usuarioBySupervisor == null) {
	    if (other.usuarioBySupervisor != null) {
		return false;
	    }
	} else if (!usuarioBySupervisor.equals(other.usuarioBySupervisor)) {
	    return false;
	}
	return true;
    }

    /*
     * (non-Javadoc)
     * 
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
	return baseVideoDeteccao.getId() + "."
		+ usuarioBySupervisor.getId() + "." + usuarioByEscravo.getId() + "." + status;
    }

}
