package br.edu.ufrpe.uag.projetao.model;
// Generated 26/04/2016 23:17:23 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import br.edu.ufrpe.uag.projetao.interfaces.InterfaceEntity;

/**
 * Perfil generated by hbm2java
 */

@Entity
@Table(name = "perfil", schema = "public")
public class Perfil implements InterfaceEntity {
    private String nome;
    private String descricao;
    private Set<Usuario> usuarios = new HashSet<>(0);

    public Perfil() {
    }

    public Perfil(String nome, String descricao) {
	this.nome = nome;
	this.descricao = descricao;
    }

    public Perfil(String nome, String descricao, Set<Usuario> usuarios) {
	this.nome = nome;
	this.descricao = descricao;
	this.usuarios = usuarios;
    }

    @Id

    @Column(name = "nome", unique = true, nullable = false, length = 100)
    public String getNome() {
	return this.nome;
    }

    public void setNome(String nome) {
	this.nome = nome;
    }

    @Column(name = "descricao", nullable = false)
    public String getDescricao() {
	return this.descricao;
    }

    public void setDescricao(String descricao) {
	this.descricao = descricao;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "perfil")
    public Set<Usuario> getUsuarios() {
	return this.usuarios;
    }

    public void setUsuarios(Set<Usuario> usuarios) {
	this.usuarios = usuarios;
    }

    @Override
    public int hashCode() {
	int hash = 5;
	hash = 37 * hash + Objects.hashCode(this.nome);
	return hash;
    }

    @Override
    public boolean equals(Object obj) {
	if (this == obj) {
	    return true;
	}
	if (obj == null) {
	    return false;
	}
	if (getClass() != obj.getClass()) {
	    return false;
	}
	final Perfil other = (Perfil) obj;
	return Objects.equals(this.nome, other.nome);
    }

    @Override
    public String toString() {
	return nome;
    }

}
