package br.edu.ufrpe.uag.projetao.model;
// Generated 20/04/2016 21:21:23 by Hibernate Tools 4.3.1

import br.edu.ufrpe.uag.projetao.interfaces.InterfaceEntity;
import java.util.Objects;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RespostaTexto generated by hbm2java
 */
@Entity
@Table(name = "resposta_texto", schema = "public"
)
public class RespostaTexto implements java.io.Serializable, InterfaceEntity {

    private RespostaTextoId id;
    private EscolhaClasseTexto escolhaClasseTexto;
    private AlocacaoTexto alocacaoTexto;

    public RespostaTexto() {
    }

    public RespostaTexto(RespostaTextoId id, EscolhaClasseTexto escolhaClasseTexto) {
        this.id = id;
        this.escolhaClasseTexto = escolhaClasseTexto;
    }

    @EmbeddedId

    @AttributeOverrides({
        @AttributeOverride(name = "escolhaTexto", column = @Column(name = "escolha_texto", nullable = false)),
        @AttributeOverride(name = "alocacaoTexto", column = @Column(name = "alocacao_texto", nullable = false))})
    public RespostaTextoId getId() {
        return this.id;
    }

    public void setId(RespostaTextoId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "escolha_texto", nullable = false, insertable = false, updatable = false)
    public EscolhaClasseTexto getEscolhaClasseTexto() {
        return this.escolhaClasseTexto;
    }

    public void setEscolhaClasseTexto(EscolhaClasseTexto escolhaClasseTexto) {
        this.escolhaClasseTexto = escolhaClasseTexto;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "alocacao_texto", nullable = false, insertable = false, updatable = false)
    public AlocacaoTexto getAlocacaoTexto() {
        return this.alocacaoTexto;
    }

    public void setAlocacaoTexto(AlocacaoTexto alocacaoTexto) {
        this.alocacaoTexto = alocacaoTexto;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 41 * hash + Objects.hashCode(this.id);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final RespostaTexto other = (RespostaTexto) obj;
        return Objects.equals(this.id, other.id);
    }

    @Override
    public String toString() {
        return "RespostaTexto{" + "escolhaClasseTexto=" + escolhaClasseTexto + ", alocacaoTexto=" + alocacaoTexto + '}';
    }

}
