package br.edu.ufrpe.uag.projetao.model;
// Generated 20/04/2016 21:21:23 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RespostaTextoId generated by hbm2java
 */
@Embeddable
public class RespostaTextoId implements java.io.Serializable {

    private int escolhaTexto;
    private int alocacaoTexto;

    public RespostaTextoId() {
    }

    public RespostaTextoId(int escolhaTexto, int alocacaoTexto) {
        this.escolhaTexto = escolhaTexto;
        this.alocacaoTexto = alocacaoTexto;
    }

    @Column(name = "escolha_texto", nullable = false)
    public int getEscolhaTexto() {
        return this.escolhaTexto;
    }

    public void setEscolhaTexto(int escolhaTexto) {
        this.escolhaTexto = escolhaTexto;
    }

    @Column(name = "alocacao_texto", nullable = false)
    public int getAlocacaoTexto() {
        return this.alocacaoTexto;
    }

    public void setAlocacaoTexto(int alocacaoTexto) {
        this.alocacaoTexto = alocacaoTexto;
    }

    @Override
    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof RespostaTextoId)) {
            return false;
        }
        RespostaTextoId castOther = (RespostaTextoId) other;

        return (this.getEscolhaTexto() == castOther.getEscolhaTexto())
                && (this.getAlocacaoTexto() == castOther.getAlocacaoTexto());
    }

    @Override
    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getEscolhaTexto();
        result = 37 * result + this.getAlocacaoTexto();
        return result;
    }

}
